### ISSUE TITLE
support hystrix config in global way

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-rpc-boot-projects#135]
### Your question

describe your question clearly

### Your scenes

https://github.com/alipay/sofa-rpc/issues/189

### Your advice

describe the advice or solution you'd like

### Environment

- Starter version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ScienJus** [comment]
想了一下，这个功能和 #136 都比较通用以及不难实现，而且有 https://github.com/alipay/sofa-boot/pull/282 也基本上很好用了。不过 `SetterFactory` 和 `FallbackFactory` 的配置就有些麻烦了。

感觉暂时应该先在 `SofaHystrixConfig` 开一个口子，允许用户直接调用 `registerGlobalSetterFactory` 和 `registerGlobalSetterFactory` 注册全局的实现（当前是 `DefaultSetterFactory` 和 `null`）。

这样用户在 xml 和 annotation 下即使没办法获取 `ConsumerConfig` 注册不同的实现，也可以通过全局的实现中判断实际执行的 `invoker/request` 并返回不同逻辑，至少能让这两个功能在 xml 和 annotation 下可用？

意下如何？

（以及其他关于 hystrix 的相关支持和 issue，也都可以指派给我）

**Comment by leizhiyuan** [comment]
可以的，那你可以提给sofaboot 上

https://github.com/alipay/sofa-rpc-boot-projects/pull/137 这个我就先不继续了。

**Comment by ScienJus** [comment]
#136 和 #137 应该没有变化，我先把 `globalSetterFactory/globalFallbackFactory` 加到 sofa-rpc 里，暂时让用户直接用 `SofaHystrixConfig`（无论是 sofa-rpc 还是 sofa-boot）。

**Comment by leizhiyuan** [comment]
好的。
