### ISSUE TITLE
sofa-rpc是否有计划升级nacos版本?

### ISSUE THREAD

**Issue by vidytu** [sofastack/sofa-rpc-boot-projects#171]
目前nacos已发布1.0.0版本，且API变化后，原API不再支持，sofa-rpc是否有计划升级版本？

**Comment by ujjboy** [comment]
@vidytu Yes, because of incompatible API, we will upgrade it in next minor version.  Can you help upgrade it?

**Comment by vidytu** [comment]
I will try

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-rpc-boot-projects/pull/176
