### ISSUE TITLE
SofaBootRpcAutoConfiguration中的configureProcessorMap处理不支持自定义registry

### ISSUE THREAD

**Issue by iamcyw** [sofastack/sofa-rpc-boot-projects#173]
### Your question

在目前的com.alipay.sofa.rpc.boot.SofaBootRpcAutoConfiguration#configureProcessorMap中，是按照系统支持的registry写死的，不支持自定义registry，这违背了sofa-rpc的扩展性

### Your scenes
在sofa-boot中使用自定义的registry

### Your advice

将现在的RegistryConfigureProcessor改成用protocol的parserFactory，对系统支持的protocol定义parser，对于不支持的protocol提供默认的parser，考虑能否支持自定义注册parser。

**Comment by iamcyw** [comment]
这事没人管管吗？现在在不加exclude的清空下，都没有办法覆盖这个bean

**Comment by khotyn** [comment]
@leizhiyuan @ujjboy 你们帮忙看下哦。

**Comment by JervyShi** [comment]
@iamcyw 可以提个 PR 解决这个问题么？

**Comment by iamcyw** [comment]
> @iamcyw 可以提个 PR 解决这个问题么？

可以看看我另外一个和此事有关的issue吗？我现在选择的方案是注册registryConfigMap这个bean，但是在SofaBootRpcAutoConfiguration中没有使用

**Comment by iamcyw** [comment]
> @iamcyw 可以提个 PR 解决这个问题么？

或者可以在configureProcessorMap上加入@Conditional来支持覆盖这个bean吗？这样的改动是最小的，而且也是一个不错的扩展性方案
我可以做这个事情，但是我想我们能有一个处理的共识可以吗？

**Comment by leizhiyuan** [comment]
如果你这边最近需要使用测试，可以通过注解来覆盖，

测试确认可行后，长期的方案，可以提个 PR 来统一解决？这样其他的人就不再需要覆盖了～

**Comment by leizhiyuan** [comment]
@iamcyw
